import type { StyleReport } from '@/lib/types'

export function generateCssVariables(report: StyleReport): string {
  const { colors, colorSystem, typography, designDetails, gradients } = report

  // Prefer colorSystem (Codex's precise extraction) with fallback to colors array
  const bgHex      = colorSystem?.pageBackground?.hex   || colorSystem?.heroBackground?.hex || colors.find(c => c.role === 'background')?.hex || '#ffffff'
  const surfaceHex = colorSystem?.surface?.hex          || colors.find(c => c.role === 'surface')?.hex || '#f5f5f5'
  const primaryHex = colorSystem?.primaryAction?.hex    || colors.find(c => c.role === 'primary')?.hex || '#000000'
  const secondaryHex = colorSystem?.secondaryAction?.hex || colors.find(c => c.role === 'secondary')?.hex
  const accentHex  = colorSystem?.contentColors?.[0]?.hex || colors.find(c => c.role === 'accent')?.hex
  const textHex    = colorSystem?.textPrimary?.hex      || colors.find(c => c.role === 'text')?.hex || '#1a1a1a'
  const textSecHex = colorSystem?.textSecondary?.hex    || null
  const borderHex  = colorSystem?.border?.hex           || colors.find(c => c.role === 'border')?.hex || '#e5e5e5'

  // Use exact extracted CSS values when available
  const radius     = designDetails.cssRadius || inferRadius(designDetails.borderRadius)
  const shadow     = designDetails.cssShadow || inferShadow(designDetails.shadowStyle)
  const transition = inferTransition(designDetails.animationTendency)

  let css = `/* Generated by StyleLens — ${report.sourceLabel} */
/* Color Mode: ${designDetails.colorMode} */

:root {
  /* ── Colors ─────────────────────────────────── */
  --color-bg: ${bgHex.toUpperCase()};
  --color-surface: ${surfaceHex.toUpperCase()};
  --color-primary: ${primaryHex.toUpperCase()};`

  if (secondaryHex) css += `\n  --color-secondary: ${secondaryHex.toUpperCase()};`
  if (accentHex)    css += `\n  --color-accent: ${accentHex.toUpperCase()};`

  // Extra accent colors from contentColors
  if (colorSystem?.contentColors && colorSystem.contentColors.length > 1) {
    colorSystem.contentColors.slice(1).forEach((c, i) => {
      css += `\n  --color-accent-${i + 2}: ${c.hex.toUpperCase()};`
    })
  }

  css += `\n  --color-text: ${textHex.toUpperCase()};`
  if (textSecHex) css += `\n  --color-text-secondary: ${textSecHex.toUpperCase()};`
  css += `\n  --color-border: ${borderHex.toUpperCase()};`

  // HSL companion variables for opacity/lightness variants
  const bgToken    = colorSystem?.pageBackground || colorSystem?.heroBackground || colors.find(c => c.role === 'background')
  const primaryToken = colorSystem?.primaryAction || colors.find(c => c.role === 'primary')
  if (bgToken?.hsl)      css += `\n  --color-bg-hsl: ${bgToken.hsl}; /* for opacity variants */`
  if (primaryToken?.hsl) css += `\n  --color-primary-hsl: ${primaryToken.hsl}; /* for hover/alpha variants */`

  if (gradients.length > 0) {
    css += `\n\n  /* ── Gradients ──────────────────────────────── */`
    gradients.forEach((g, i) => {
      css += `\n  --gradient-${i + 1}: ${g.css}; /* ${g.description} */`
    })
  }

  css += `
  /* ── Typography ─────────────────────────────── */
  --font-family: ${typography.fontFamily};
  --font-weight-heading: ${typography.headingWeight};
  --font-weight-body: ${typography.bodyWeight};
  --line-height-base: ${typography.lineHeight};
  --letter-spacing-base: ${typography.letterSpacing};

  /* ── Geometry ────────────────────────────────── */
  --radius-base: ${radius};
  --shadow-base: ${shadow};
  --border-style: ${designDetails.borderStyle};

  /* ── Motion ──────────────────────────────────── */
  --transition-base: ${transition};
}`

  return css
}

function inferRadius(d: string): string {
  const s = d.toLowerCase()
  if (s.includes('sharp') || s.includes('none') || s.includes('0px')) return '0px'
  if (s.includes('full') || s.includes('pill')) return '9999px'
  if (s.includes('large') || s.includes('xl')) return '16px'
  if (s.includes('medium') || s.includes('moderate')) return '8px'
  if (s.includes('small') || s.includes('subtle')) return '4px'
  return '6px'
}
function inferShadow(d: string): string {
  const s = d.toLowerCase()
  if (s.includes('none') || s.includes('flat') || s.includes('no shadow')) return 'none'
  if (s.includes('heavy') || s.includes('strong')) return '0 20px 60px rgba(0,0,0,0.25)'
  if (s.includes('medium') || s.includes('moderate')) return '0 4px 16px rgba(0,0,0,0.12)'
  return '0 1px 4px rgba(0,0,0,0.08)'
}
function inferTransition(d: string): string {
  const s = d.toLowerCase()
  let duration = '200ms', easing = 'ease-out'
  if (s.includes('fast') || s.includes('instant')) duration = '120ms'
  if (s.includes('slow') || s.includes('deliberate')) duration = '350ms'
  if (s.includes('bouncy') || s.includes('spring')) easing = 'cubic-bezier(0.34, 1.56, 0.64, 1)'
  if (s.includes('linear')) easing = 'linear'
  return `all ${duration} ${easing}`
}
