import type { StyleReport } from '@/lib/types'

export function generateCssVariables(report: StyleReport): string {
  const { colors, typography, designDetails, gradients } = report

  const radius = designDetails.cssRadius || inferRadius(designDetails.borderRadius)
  const shadow = designDetails.cssShadow || inferShadow(designDetails.shadowStyle)
  const transition = inferTransition(designDetails.animationTendency)

  // Build unique var names — same role gets --color-accent, --color-accent-2, etc.
  const roleCounts: Record<string, number> = {}
  const colorEntries: { varName: string; hex: string; hsl: string; name: string; description: string }[] = []

  for (const c of colors) {
    roleCounts[c.role] = (roleCounts[c.role] || 0) + 1
    const count = roleCounts[c.role]
    const base = roleToVarBase(c.role)
    const varName = count === 1 ? base : `${base}-${count}`
    colorEntries.push({ varName, hex: c.hex.toUpperCase(), hsl: c.hsl, name: c.name, description: c.description })
  }

  let css = `/* Generated by StyleLens — ${report.sourceLabel} */
/* Color Mode: ${designDetails.colorMode} */

:root {
  /* ── Colors ─────────────────────────────────── */\n`

  for (const entry of colorEntries) {
    css += `  ${entry.varName}: ${entry.hex};`
    css += ` /* ${entry.name}${entry.description ? ' — ' + entry.description : ''} */\n`
    if (entry.hsl) {
      css += `  ${entry.varName}-hsl: ${entry.hsl}; /* for opacity/lightness variants */\n`
    }
  }

  if (gradients.length > 0) {
    css += `\n  /* ── Gradients ──────────────────────────────── */\n`
    gradients.forEach((g, i) => {
      css += `  --gradient-${i + 1}: ${g.css}; /* ${g.description} */\n`
    })
  }

  css += `
  /* ── Typography ─────────────────────────────── */
  --font-family: ${typography.fontFamily};
  --font-weight-heading: ${typography.headingWeight};
  --font-weight-body: ${typography.bodyWeight};
  --line-height-base: ${typography.lineHeight};
  --letter-spacing-base: ${typography.letterSpacing};

  /* ── Geometry ────────────────────────────────── */
  --radius-base: ${radius};
  --shadow-base: ${shadow};
  --border-style: ${designDetails.borderStyle};

  /* ── Motion ──────────────────────────────────── */
  --transition-base: ${transition};
}`

  return css
}

function roleToVarBase(role: string): string {
  const map: Record<string, string> = {
    background: '--color-bg',
    surface:    '--color-surface',
    primary:    '--color-primary',
    secondary:  '--color-secondary',
    accent:     '--color-accent',
    text:       '--color-text',
    border:     '--color-border',
    other:      '--color-other',
  }
  return map[role] || `--color-${role}`
}

function inferRadius(description: string): string {
  const d = description.toLowerCase()
  if (d.includes('sharp') || d.includes('none') || d.includes('0px')) return '0px'
  if (d.includes('full') || d.includes('pill')) return '9999px'
  if (d.includes('large') || d.includes('xl')) return '16px'
  if (d.includes('medium') || d.includes('moderate')) return '8px'
  if (d.includes('small') || d.includes('subtle')) return '4px'
  return '6px'
}

function inferShadow(description: string): string {
  const d = description.toLowerCase()
  if (d.includes('none') || d.includes('flat') || d.includes('no shadow')) return 'none'
  if (d.includes('heavy') || d.includes('strong') || d.includes('dramatic')) return '0 20px 60px rgba(0,0,0,0.25)'
  if (d.includes('medium') || d.includes('moderate')) return '0 4px 16px rgba(0,0,0,0.12)'
  return '0 1px 4px rgba(0,0,0,0.08)'
}

function inferTransition(description: string): string {
  const d = description.toLowerCase()
  let duration = '200ms'
  let easing = 'ease-out'
  if (d.includes('fast') || d.includes('instant')) duration = '120ms'
  if (d.includes('slow') || d.includes('deliberate')) duration = '350ms'
  if (d.includes('bouncy') || d.includes('spring')) easing = 'cubic-bezier(0.34, 1.56, 0.64, 1)'
  if (d.includes('linear')) easing = 'linear'
  return `all ${duration} ${easing}`
}
