import type { StyleReport } from '@/lib/types'

export function generateTailwindConfig(report: StyleReport): string {
  const { colors, typography, designDetails } = report

  // Build color palette — same role gets DEFAULT, then numeric suffixes
  const colorsByRole: Record<string, string[]> = {}
  for (const c of colors) {
    if (!colorsByRole[c.role]) colorsByRole[c.role] = []
    colorsByRole[c.role].push(c.hex.toUpperCase())
  }

  const colorLines: string[] = []
  for (const [role, hexes] of Object.entries(colorsByRole)) {
    if (hexes.length === 1) {
      colorLines.push(`        ${role}: '${hexes[0]}',`)
    } else {
      colorLines.push(`        ${role}: {`)
      hexes.forEach((hex, i) => {
        colorLines.push(`          ${i === 0 ? 'DEFAULT' : i + 1}: '${hex}',`)
      })
      colorLines.push(`        },`)
    }
  }

  // Font family as array for Tailwind
  const fontFamilyArray = typography.fontFamily
    .split(',')
    .map(f => `'${f.trim()}'`)
    .join(', ')

  const radiusValue = designDetails.cssRadius || inferRadius(designDetails.borderRadius)
  const shadowValue = designDetails.cssShadow || inferShadow(designDetails.shadowStyle)

  // fontWeight: use numeric keys so Tailwind utilities work (font-[700] or extend scale)
  const headingW = String(typography.headingWeight)
  const bodyW    = String(typography.bodyWeight)

  return `/** @type {import('tailwindcss').Config} */
// Generated by StyleLens — ${report.sourceLabel}
// Usage: import this into your tailwind.config.js theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
${colorLines.join('\n')}
      },
      fontFamily: {
        // Usage: font-sans
        sans: [${fontFamilyArray}, 'system-ui', 'sans-serif'],
      },
      fontWeight: {
        // Usage: font-bold maps to heading weight, font-normal maps to body weight
        // These are standard Tailwind weight keys — override with your extracted values:
        bold:   '${headingW}', // heading weight → use: font-bold
        normal: '${bodyW}',   // body weight    → use: font-normal
      },
      lineHeight: {
        // Usage: leading-brand
        brand: '${typography.lineHeight}',
      },
      letterSpacing: {
        // Usage: tracking-brand
        brand: '${typography.letterSpacing}',
      },
      borderRadius: {
        // Usage: rounded-brand
        brand: '${radiusValue}',
      },
      boxShadow: {
        // Usage: shadow-brand
        brand: '${shadowValue}',
      },
    },
  },
}
`
}

function inferRadius(description: string): string {
  const d = description.toLowerCase()
  if (d.includes('sharp') || d.includes('none') || d.includes('0')) return '0px'
  if (d.includes('full') || d.includes('pill')) return '9999px'
  if (d.includes('large') || d.includes('xl')) return '16px'
  if (d.includes('medium') || d.includes('moderate')) return '8px'
  if (d.includes('small') || d.includes('subtle')) return '4px'
  return '6px'
}

function inferShadow(description: string): string {
  const d = description.toLowerCase()
  if (d.includes('none') || d.includes('flat') || d.includes('no shadow')) return 'none'
  if (d.includes('heavy') || d.includes('strong') || d.includes('dramatic')) return '0 20px 60px rgba(0,0,0,0.3)'
  if (d.includes('subtle') || d.includes('minimal') || d.includes('soft')) return '0 1px 4px rgba(0,0,0,0.08)'
  return '0 4px 16px rgba(0,0,0,0.12)'
}
