import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import * as cheerio from "cheerio";

import { buildContentFromMarkdown } from "./content.mjs";
import { runtimeScript, runtimeStyle } from "./editable-runtime.mjs";
import { loadTemplate } from "./templates.mjs";

const execFileAsync = promisify(execFile);
const require = createRequire(import.meta.url);
const TAILWIND_CLI_PATH = require.resolve("tailwindcss/lib/cli.js");

export async function buildHtmlFromText(options) {
  const text = options.text;
  const inputPath = options.inputPath || "input.md";
  const pageType = options.type || "product-website";
  const templateName = options.template || "website-01-fui";

  if (typeof text !== "string" || !text.trim()) throw new Error("缺少输入文本：text");
  if (!["product-website", "product_website"].includes(pageType)) {
    throw new Error(`第一版只支持产品官网：${pageType}`);
  }

  const template = await loadTemplate(templateName);
  assertTemplateMatchesPageType(pageType, template);
  const content = buildContentFromMarkdown(text, inputPath);
  const $ = cheerio.load(template.html, { decodeEntities: false });

  $("title").text(`${content.title} - AI HTML Publisher`);
  removeFakeLinks($);

  if (["website-02-soft-surrealism", "soft-surrealism"].includes(templateName)) {
    injectSoftSurrealism($, content);
  } else if (["website-03-red-clay", "red-clay"].includes(templateName)) {
    injectRedClay($, content);
  } else if (["website-04-premium-midnight", "premium-midnight"].includes(templateName)) {
    injectPremiumMidnight($, content);
  } else if (["website-05-voltflow-cyber-saas", "voltflow-cyber-saas", "cyber-saas"].includes(templateName)) {
    injectVoltflowCyberSaas($, content);
  } else if (["website-07-blueprint-agent-platform", "blueprint-agent-platform", "blueprint-agent"].includes(templateName)) {
    injectBlueprintAgentPlatform($, content);
  } else if (["website-08-editorial-apple-tech", "editorial-apple-tech", "apple-tech"].includes(templateName)) {
    injectEditorialAppleTech($, content);
  } else if (["website-09-blue-shift-portfolio", "blue-shift-portfolio", "blue-shift"].includes(templateName)) {
    injectBlueShiftPortfolio($, content);
  } else {
    injectFi($, content);
  }

  stripTemplateEditorArtifacts($);
  sanitizeGeneratedOutput($);
  cleanKnownInternalRemnants($);
  await inlineTailwindStyles($);
  assignEditIds($);
  const templateId = template.config.id || template.name || templateName;
  const themeColor = templateThemeColor(template.config, templateId);
  const themeConfig = templateThemeConfig(template.config, themeColor);
  injectRuntime($, content.title, templateId, themeColor, themeConfig);

  return $.html();
}

function assertTemplateMatchesPageType(pageType, template) {
  if (["product-website", "product_website"].includes(pageType) && template.kind !== "website") {
    throw new Error(`模板类型不匹配：产品官网只能使用 website 模板，当前模板是 ${template.name}`);
  }
}

function injectSoftSurrealism($, content) {
  setByKey($, "brand_name", content.title);
  setByKey($, "nav_1", "问题");
  setByKey($, "nav_2", "能力");
  setByKey($, "nav_3", "行动");
  setByKey($, "hero_title", `${escapeHtml(content.title)}<br><span class="motion-smudge text-transparent bg-clip-text bg-gradient-to-r from-soft-white via-cloud-pink to-soft-white">可编辑 HTML</span>`, true);
  setByKey($, "hero_desc", content.subtitle);
  setByKey($, "hero_btn_primary", "查看能力");
  setByKey($, "hero_btn_secondary", "直接编辑");
  setByKey($, "phil_tag", "Product");
  setByKey($, "phil_title", `${escapeHtml(content.title)}<br>把内容变成页面。`, true);
  setByKey($, "phil_desc", content.subtitle);

  const firstFeature = content.features[0] || { title: content.title, desc: content.subtitle };
  setByKey($, "feat_title", firstFeature.title);
  setByKey($, "feat_desc", firstFeature.desc);

  fillTriplet($, content.values, [
    ["val1_title", "val1_desc"],
    ["val2_title", "val2_desc"],
    ["val3_title", "val3_desc"]
  ]);

  setByKey($, "cta_title", `${escapeHtml(content.title)}<br>可以继续编辑。`, true);
  setByKey($, "cta_desc", "直接点击页面文字即可修改，需要细调时打开高级编辑，最后导出完整 HTML。");
  setByKey($, "cta_btn", "导出 HTML");
  setByKey($, "foot_copy", `© 2026 ${content.title}`);
  setByKey($, "foot_slogan", "Generated by AI HTML Publisher");

  removeSections($, ["gallery", "statistics", "testimonials", "literature"]);
}

function injectFi($, content) {
  const features = content.features.length ? content.features : [{ title: content.title, desc: content.subtitle }];

  setText($('header [data-editable="true"]').first(), content.title);
  $("header nav span").eq(0).text("问题");
  $("header nav span").eq(1).text("能力");
  $("header nav span").eq(2).text("流程");
  $("header nav span").eq(3).text("行动");

  setText($('[data-section="hero"] h1').first(), content.title);
  setText($('[data-section="hero"] h2').first(), "可编辑 HTML 页面生成器");
  setText($('[data-section="hero"] .fui-btn').first(), "查看能力");

  if (content.painPoints.length) {
    fillPairs($, "pain-points", "h3", "p", content.painPoints);
  } else {
    removeSections($, ["pain-points"]);
  }

  setText($('[data-section="status"] p').first(), content.subtitle);
  fillPairs($, "features", "h3", "p", features);
  fillPairs($, "functions", "h4", "p", features);
  fillPairs($, "core-selling-points", "h3", "p", content.values.length ? content.values : features);

  if (content.flow.length) {
    const flowItems = content.flow.map((item) => ({ title: item, desc: "按材料执行" }));
    fillPairs($, "business-logic", "h4", "p", flowItems);
  } else {
    removeSections($, ["business-logic"]);
  }

  setText($('[data-section="cta"] .text-white').last(), `直接点击文字，修改 ${content.title} 页面内容。`);
  setText($('[data-section="cta"] button').first(), "保存并导出");

  removeSections($, ["showcase", "architecture", "product-value", "analytics", "social-media"]);
  sanitizeFiDecorations($);
}

function injectRedClay($, content) {
  const features = content.features.length ? content.features : [{ title: content.title, desc: content.subtitle }];
  const values = content.values.length ? content.values : features;
  const painPoints = content.painPoints.length ? content.painPoints : features.slice(0, 3);
  const flow = content.flow.length ? content.flow : ["输入材料", "选择模板", "生成页面", "编辑导出"];

  setByKey($, "header_logo", content.title);
  setByKey($, "header_nav_problem", "问题");
  setByKey($, "header_nav_solutions", "方案");
  setByKey($, "header_nav_academy", "能力");
  setByKey($, "header_nav_facilities", "交付");
  setByKey($, "header_nav_workflow", "流程");

  setByKey($, "hero_tag_num", "#01");
  setByKey($, "hero_tag_name", "@AI_HTML");
  setByKey($, "hero_title_sub_1", "STABLE");
  setByKey($, "hero_title_main_1", content.title);
  setByKey($, "hero_title_sub_2", "EDITABLE");
  setByKey($, "hero_title_main_2", "HTML");

  setByKey($, "statement_text", `${escapeHtml(content.title)}<br>把材料变成可编辑页面。`, true);

  setByKey($, "problem_tag_num", "#02");
  setByKey($, "problem_tag_name", "@THE_PROBLEM");
  setByKey($, "problem_title", "不可控的页面生成");
  setByKey($, "problem_subtitle", content.subtitle);
  fillKeyPairs($, painPoints, [
    ["problem_item_1_title", "problem_item_1_desc"],
    ["problem_item_2_title", "problem_item_2_desc"],
    ["problem_item_3_title", "problem_item_3_desc"]
  ]);

  setByKey($, "solutions_tag_num", "#03");
  setByKey($, "solutions_tag_name", "@THE_SYSTEM");
  setByKey($, "solutions_title", "模板驱动的稳定方案");
  fillKeyPairs($, features, [
    ["solutions_item_1_title", "solutions_item_1_desc"],
    ["solutions_item_2_title", "solutions_item_2_desc"],
    ["solutions_item_3_title", "solutions_item_3_desc"]
  ]);

  setByKey($, "academy_tag_num", "#04");
  setByKey($, "academy_tag_name", "@EDITOR");
  setByKey($, "academy_title", "页面内编辑能力");
  fillKeyPairs($, values, [
    ["academy_item_1_title", "academy_item_1_desc"],
    ["academy_item_2_title", "academy_item_2_desc"]
  ]);

  setByKey($, "facilities_tag_num", "#05");
  setByKey($, "facilities_tag_name", "@DELIVERY");
  setByKey($, "facilities_title", "单文件本地交付");
  setByKey($, "facilities_desc", "生成后的 HTML 可以直接打开、保存、继续编辑，并导出新的完整文件。");
  setByKey($, "facilities_item_1_title", "无需账号");
  setByKey($, "facilities_item_1_desc", "第一版不做登录、数据库和在线发布。");
  setByKey($, "facilities_item_2_title", "可直接导出");
  setByKey($, "facilities_item_2_desc", "修改后的页面可以导出为新的 HTML。");

  setByKey($, "workflow_tag_num", "#06");
  setByKey($, "workflow_tag_name", "@WORKFLOW");
  setByKey($, "workflow_title", "从材料到页面");
  fillFlowSteps($, flow);

  setByKey($, "cta_tag_num", "#99");
  setByKey($, "cta_tag_name", "@EXPORT");
  setByKey($, "cta_title", "INLINE<br>EDIT", true);
  setByKey($, "cta_desc", "直接点击文字修改，需要时用高级编辑微调样式、链接和模块。");
  setByKey($, "cta_button", "高级编辑");

  setByKey($, "footer_brand", `${escapeHtml(content.title)}<br>HTML`, true);
  setByKey($, "footer_desc", "由现有模板生成，保留模板视觉，不让 AI 从零设计页面。");
  setByKey($, "footer_copyright", "本地生成 · 可编辑 · 可导出");
  setByKey($, "footer_connect_title", "OUTPUT");
  setByKey($, "footer_link_xhs", "保存到浏览器本地");
  setByKey($, "footer_link_wechat", "导出完整 HTML");
  setByKey($, "footer_link_email", "恢复初始版本");
  setByKey($, "footer_phone", "无账号 · 无数据库 · 无在线发布");
  setByKey($, "footer_wechat_pro_title", "INLINE EDIT");
  setByKey($, "footer_wechat_pro_desc", "点击页面文字即可修改，高级编辑可调整文字块和模块。");
  setByKey($, "footer_qr_placeholder", "HTML");

  $('[data-key="footer_link_email"]').removeAttr("href");
}

function injectPremiumMidnight($, content) {
  const features = content.features.length ? content.features : [{ title: content.title, desc: content.subtitle }];
  const values = content.values.length ? content.values : features;
  const painPoints = content.painPoints.length ? content.painPoints : features;
  const flow = content.flow.length ? content.flow : ["输入材料", "选择模板", "生成页面"];

  setBySlot($, "logo-name", content.title);
  setBySlot($, "nav-link-1", "首页");
  setBySlot($, "nav-link-2", "产品");
  setBySlot($, "nav-link-3", "数据");
  setBySlot($, "nav-link-4", "问题");
  setBySlot($, "nav-cta-text", "开始体验");

  setBySlot($, "hero-badge", "PREMIUM MIDNIGHT");
  setBySlot($, "hero-title", `${escapeHtml(content.title)}<br><span class="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-500">高端产品官网</span>`, true);
  setBySlot($, "hero-subtitle", content.subtitle);
  setBySlot($, "hero-primary-cta", "开始体验");
  setBySlot($, "hero-secondary-cta", "查看产品演示");

  setBySlot($, "showcase-title", features[0]?.title || content.title);
  setBySlot($, "showcase-desc", features[0]?.desc || content.subtitle);
  setBySlot($, "showcase-tab-1", "核心能力");
  setBySlot($, "showcase-tab-2", "自动流程");
  setBySlot($, "showcase-tab-3", "价值测算");
  setBySlot($, "dash-room-1", features[1]?.title || "核心功能已就绪");
  setBySlot($, "dash-room-2", features[2]?.title || "关键流程已接入");
  setBySlot($, "dispatch-item-1", flow[0]);
  setBySlot($, "dispatch-item-2", flow[1]);
  setBySlot($, "rev-detail-1", values[0]?.title || "核心价值持续提升");
  setBySlot($, "rev-detail-2", values[0]?.desc || content.subtitle);

  setBySlot($, "val-badge", "VALUE MODEL");
  setBySlot($, "val-title", `${escapeHtml(content.title)}<br>价值结构洞察`, true);
  setBySlot($, "val-desc", values[0]?.desc || content.subtitle);

  setBySlot($, "metrics-title", "关键指标与增长态势");
  setBySlot($, "metrics-desc", content.subtitle);
  ["bar-label-1", "bar-label-2", "bar-label-3", "bar-label-4", "bar-label-5"].forEach((slot, index) => {
    setBySlot($, slot, features[index]?.title || `阶段 ${index + 1}`);
  });

  setBySlot($, "arch-title", "产品能力链路架构");
  setBySlot($, "arch-desc", "从输入、处理到交付，形成稳定的产品闭环。");
  [["node-title-1", "node-desc-1"], ["node-title-2", "node-desc-2"], ["node-title-3", "node-desc-3"]].forEach(([titleSlot, descSlot], index) => {
    const item = features[index] || features[0];
    setBySlot($, titleSlot, item?.title);
    setBySlot($, descSlot, item?.desc);
  });

  setBySlot($, "problem-title", "直击核心问题");
  setBySlot($, "problem-subtitle", "用清晰流程解决低效与不确定。");
  setBySlot($, "problem-desc", painPoints[0]?.desc || content.subtitle);
  [["card-title-1", "card-desc-1"], ["card-title-2", "card-desc-2"], ["card-title-3", "card-desc-3"], ["card-title-4", "card-desc-4"]].forEach(([titleSlot, descSlot], index) => {
    const item = painPoints[index] || features[index] || features[0];
    setBySlot($, titleSlot, item?.title);
    setBySlot($, descSlot, item?.desc);
  });

  setBySlot($, "cta-title", `${content.title} 可以继续编辑和导出`);
  setBySlot($, "cta-subtitle", "直接点击页面文字和数字即可修改，需要时打开高级编辑调整样式和模块。");
  setBySlot($, "cta-btn", "高级编辑");
}

function injectVoltflowCyberSaas($, content) {
  const features = content.features.length ? content.features : [{ title: content.title, desc: content.subtitle }];
  const painPoints = content.painPoints.length ? content.painPoints : features.slice(0, 3);
  const values = content.values.length ? content.values : features;
  const flow = content.flow.length ? content.flow : ["输入材料", "选择模板", "生成页面", "编辑导出"];

  setBySlot($, "logo-tag", content.title);
  setBySlot($, "version-tag", "AI HTML PUBLISHER");
  setBySlot($, "nav-link-1", "问题");
  setBySlot($, "nav-link-2", "能力");
  setBySlot($, "nav-link-3", "流程");
  setBySlot($, "nav-link-4", "行动");
  setBySlot($, "header-roi-link", "// EDIT HTML");
  setBySlot($, "header-cta-text", "开始编辑");

  setBySlot($, "hero-badge", "TEMPLATE DRIVEN WEBSITE");
  setBySlot($, "hero-title", `${escapeHtml(content.title)}<br><span class="text-cyber-volt">可编辑 HTML</span>`, true);
  setBySlot($, "hero-desc", content.subtitle);
  setBySlot($, "hero-primary-cta", "查看能力");
  setBySlot($, "hero-secondary-cta", "查看流程");
  setBySlot($, "hero-stats-value-1", "HTML");
  setBySlot($, "hero-stats-label-1", "单文件可导出");
  setBySlot($, "hero-stats-value-2", "0");
  setBySlot($, "hero-stats-label-2", "不依赖数据库");
  setBySlot($, "hero-stats-value-3", "可编辑");
  setBySlot($, "hero-stats-label-3", "页面内直接修改");
  setBySlot(
    $,
    "hero-terminal-output",
    `<code class="text-cyber-volt">$ ai-html-publisher build --template cyber-saas</code>
<span class="text-cyber-darkMuted"># Reading project materials ...</span>
<code class="text-white">✔ Parsed markdown content.
✔ Applied approved website template.
✔ Enabled inline editing runtime.</code>
<span class="text-cyber-volt">Output:</span>
  - page : <span class="text-white">editable HTML</span>
  - storage : <span class="text-white">local browser</span>
  - export : <span class="text-white">single file</span>
<span class="text-cyber-darkMuted">[PAGE STATUS: READY]</span>`,
    true
  );

  setBySlot($, "problem-title", "正在解决的核心问题");
  fillSlotPairs($, painPoints, [
    ["problem-card-title-1", "problem-card-desc-1"],
    ["problem-card-title-2", "problem-card-desc-2"],
    ["problem-card-title-3", "problem-card-desc-3"]
  ]);

  setBySlot($, "features-title", `${content.title} 的核心能力`);
  setBySlot($, "features-desc", content.subtitle);
  fillSlotPairs($, features, [
    ["feature-title-1", "feature-card-desc-1"],
    ["feature-title-2", "feature-card-desc-2"],
    ["feature-title-3", "feature-card-desc-3"],
    ["feature-title-4", "feature-card-desc-4"]
  ]);
  ["feature-tech-label-1", "feature-tech-label-2", "feature-tech-label-3", "feature-tech-label-4"].forEach((slot, index) => {
    setBySlot($, slot, `CAPABILITY_0${index + 1}`);
  });

  setBySlot($, "architecture-title", "从材料到页面的生成管线");
  setBySlot($, "architecture-desc", "用固定模板承接内容，让页面生成更稳定、可复用、可继续编辑。");
  flow.slice(0, 4).forEach((item, index) => {
    const step = index + 1;
    const fallback = values[index] || features[index] || features[0];
    setBySlot($, `step-num-${step}`, `STEP 0${step}`);
    setBySlot($, `step-title-${step}`, item);
    setBySlot($, `step-desc-${step}`, fallback?.desc || content.subtitle);
  });

  setBySlot($, "cta-title", `${content.title} 可以继续编辑和导出`);
  setBySlot($, "cta-desc", "直接点击文字修改，需要时打开高级编辑调整样式、链接和模块，最后导出完整 HTML 文件。");
  setBySlot($, "cta-button-text", "高级编辑");
  setBySlot($, "cta-item-04", "* 本地生成、页面内编辑、可导出为完整 HTML 文件。");

  setBySlot($, "footer-logo-tag", content.title);
  setBySlot($, "footer-description", "由 AI HTML Publisher 使用已入库模板生成，保留视觉风格，支持本地编辑和导出。");
  setFooterLinks($, [
    "页面内编辑",
    "HTML 导出",
    "模板复用",
    "产品官网",
    "能力介绍",
    "流程说明",
    "本地文件",
    "无数据库",
    "可继续编辑",
    "保存版本",
    "恢复初始",
    "导出交付"
  ]);
  setBySlot($, "copyright-text", `© 2026 ${content.title}. Generated by AI HTML Publisher.`);

  removeSections($, ["live-preview", "calculator", "proof", "pricing"]);
  $("body > script").remove();
}

function injectBlueprintAgentPlatform($, content) {
  const features = content.features.length ? content.features : [{ title: content.title, desc: content.subtitle }];
  const painPoints = content.painPoints.length ? content.painPoints : features.slice(0, 3);
  const values = content.values.length ? content.values : features;
  const flow = content.flow.length ? content.flow : ["输入材料", "选择模板", "生成页面", "编辑导出"];

  setBySlot($, "nav.logo", content.title);
  setBySlot($, "nav.link1", "问题");
  setBySlot($, "nav.link2", "方案");
  setBySlot($, "nav.link3", "流程");
  setBySlot($, "nav.link4", "编辑导出");

  setBySlot($, "text.hero.bg_letters", "HTML");
  setBySlot($, "text.hero.badge", "TEMPLATE BLUEPRINT · LOCAL HTML");
  setBySlot($, "text.hero.title", `${escapeHtml(content.title)}<br>可编辑 HTML`, true);
  setBySlot($, "text.hero.subtitle", content.subtitle);
  setBySlot($, "text.hero.btn_primary", "查看能力");
  setBySlot($, "text.hero.btn_secondary", "查看流程");

  setBySlot($, "text.problem.subtitle", "THE PROBLEM");
  setBySlot($, "text.problem.section_title", "正在解决的核心问题");
  fillDottedSlotPairs($, painPoints, [
    ["text.problem.item1_title", "text.problem.item1_desc"],
    ["text.problem.item2_title", "text.problem.item2_desc"],
    ["text.problem.item3_title", "text.problem.item3_desc"]
  ]);

  setBySlot($, "text.solution.subtitle", "THE SOLUTION");
  setBySlot($, "text.solution.section_title", `${content.title} 的解决方案`);
  setBySlot($, "text.solution.section_desc", content.subtitle);
  fillDottedSlotPairs($, features, [
    ["text.solution.item1_title", "text.solution.item1_desc"],
    ["text.solution.item2_title", "text.solution.item2_desc"],
    ["text.solution.item3_title", "text.solution.item3_desc"]
  ]);

  setBySlot($, "text.highlights.section_title", "核心能力");
  fillDottedSlotPairs($, features, [
    ["text.highlights.item1_title", "text.highlights.item1_desc"],
    ["text.highlights.item2_title", "text.highlights.item2_desc"],
    ["text.highlights.item3_title", "text.highlights.item3_desc"],
    ["text.highlights.item4_title", "text.highlights.item4_desc"]
  ]);

  setBySlot($, "text.workflow.subtitle", "WORKFLOW");
  setBySlot($, "text.workflow.section_title", "从材料到页面");
  flow.slice(0, 3).forEach((item, index) => {
    const step = index + 1;
    const fallback = values[index] || features[index] || features[0];
    setBySlot($, `text.workflow.step${step}_title`, item);
    setBySlot($, `text.workflow.step${step}_desc`, fallback?.desc || content.subtitle);
  });

  setBySlot($, "text.flow.section_title", "内容生成流转拓扑");
  flow.slice(0, 4).forEach((item, index) => {
    const step = index + 1;
    const fallback = values[index] || features[index] || features[0];
    setBySlot($, `text.flow.step${step}_name`, item);
    setBySlot($, `text.flow.step${step}_desc`, fallback?.desc || "按材料执行并保留可编辑结果。");
  });

  setBySlot($, "text.features.subtitle", "SYSTEM INTERFACE");
  setBySlot($, "text.features.section_title", "编辑控制台与页面交付");
  setBySlot($, "text.features.desc", "生成后的页面可在浏览器中预览、编辑、保存，并导出为完整 HTML 文件。");
  setBySlot($, "text.features.point1", "页面内直接编辑文字和样式");
  setBySlot($, "text.features.point2", "保留已验收模板的视觉结构");
  setBySlot($, "text.features.point3", "导出单文件 HTML 方便交付");
  setBySlot($, "text.visual.ui_title", "AI HTML PUBLISHER - EDIT TERMINAL [READY]");

  setBySlot($, "text.cta.title", `${content.title} 可以继续编辑和导出`);
  setBySlot($, "text.cta.btn", "高级编辑");
  setBySlot($, "text.footer.copyright", `© 2026 ${content.title}. Generated by AI HTML Publisher.`);
  setBySlot($, "text.footer.link1", "页面内编辑");
  setBySlot($, "text.footer.link2", "HTML 导出");
  setBySlot($, "text.footer.link3", "模板复用");
  setBySlot($, "text.footer.link4", "本地保存");

  removeSections($, ["metrics", "target_users", "use_cases", "roadmap", "social", "pricing"]);
}

function injectEditorialAppleTech($, content) {
  const features = content.features.length ? content.features : [{ title: content.title, desc: content.subtitle }];
  const painPoints = content.painPoints.length ? content.painPoints : features;
  const values = content.values.length ? content.values : features;
  const flow = content.flow.length ? content.flow : ["输入材料", "选择模板", "生成页面", "编辑导出"];

  $("footer").attr("id", "footer");
  const navLinks = $("header .nav-links a");
  ["#problem", "#solution", "#features", "#target-users", "#use-cases", "#workflow", "#footer"].forEach((href, index) => {
    navLinks.eq(index).attr("href", href);
  });

  setBySlot($, "text.header.logo", content.title);
  setBySlot($, "text.header.nav.1", "问题");
  setBySlot($, "text.header.nav.2", "方案");
  setBySlot($, "text.header.nav.3", "能力");
  setBySlot($, "text.header.nav.4", "角色");
  setBySlot($, "text.header.nav.5", "场景");
  setBySlot($, "text.header.nav.6", "流程");
  setBySlot($, "text.header.nav.7", "导出");

  setBySlot($, "text.hero.title", `${escapeHtml(content.title)}<br><i>可编辑官网</i>`, true);
  setBySlot($, "text.hero.subtitle", content.subtitle);
  setBySlot($, "text.hero.cta", "查看核心能力");
  setBySlot($, "text.hero.github", "继续编辑页面");

  setBySlot($, "text.problem.quote", `${content.title} 需要一个稳定、可编辑、能直接交付的官网。`);
  setBySlot($, "text.problem.desc", painPoints[0]?.desc || content.subtitle);

  setBySlot($, "text.solution.tag", "解决方案");
  setBySlot($, "text.solution.title", `${content.title} 的页面流转方案`);
  setBySlot($, "text.solution.desc", content.subtitle);
  fillDottedSlotPairs($, values, [
    ["text.highlight.1.title", "text.highlight.1.desc"],
    ["text.highlight.2.title", "text.highlight.2.desc"],
    ["text.highlight.3.title", "text.highlight.3.desc"]
  ]);

  setBySlot($, "text.flow.title", "从材料到页面的生成拓扑");
  setBySlot($, "text.flow.desc", "内容输入、结构识别、模板注入和本地导出串成一条清晰链路，保留模板视觉，并支持后续页面内编辑。");

  fillDottedSlotPairs($, features, [
    ["text.feature.1.title", "text.feature.1.desc"],
    ["text.feature.2.title", "text.feature.2.desc"]
  ]);
  setBySlot($, "text.visuals.title", `${content.title} 的可编辑页面预览`);
  setBySlot($, "text.visuals.placeholder", "[ 页面内容预览区 ]");

  setBySlot($, "text.users.title", "为不同角色提供清晰页面");
  fillDottedSlotPairs($, values, [
    ["text.users.1.role", "text.users.1.desc"],
    ["text.users.2.role", "text.users.2.desc"],
    ["text.users.3.role", "text.users.3.desc"]
  ]);

  setBySlot($, "text.cases.tag", "应用场景");
  setBySlot($, "text.cases.title", "适配多类产品表达");
  setBySlot($, "text.cases.desc", "适合产品介绍、能力说明、交付流程和品牌官网等场景，生成后可继续编辑细节。");
  setBySlot($, "text.cases.tab.1", "产品官网");
  setBySlot($, "text.cases.tab.2", "能力介绍");
  setBySlot($, "text.cases.tab.3", "交付流程");
  setBySlot($, "text.cases.tab.4", "本地导出");

  setBySlot($, "text.workflow.tag", "使用流程");
  setBySlot($, "text.workflow.title", "从材料到可交付 HTML");
  flow.slice(0, 3).forEach((item, index) => {
    const step = index + 1;
    const fallback = values[index] || features[index] || features[0];
    setBySlot($, `text.workflow.${step}.title`, item);
    setBySlot($, `text.workflow.${step}.desc`, fallback?.desc || content.subtitle);
  });

  setBySlot($, "text.footer.slogan", `${content.title}，由 AI HTML Publisher 生成，可本地编辑并导出。`);
  setBySlot($, "text.footer.social.email", "页面内编辑");
  setBySlot($, "text.footer.social.wechat", "保存版本");
  setBySlot($, "text.footer.social.xhs", "导出 HTML");
  setBySlot($, "text.footer.social.twitter", "模板复用");
  setBySlot($, "text.footer.copyright", `© 2026 ${content.title}. Generated by AI HTML Publisher.`);

  replaceTextFragments($, [
    ["NexusFlow", content.title],
    ["app.nexusflow.io/workspace/flow_center", "local.preview/workspace/page"]
  ], [
    ["NexusFlow Engine", "Product Engine"]
  ]);

  removeSections($, ["metrics", "pricing"]);
}

function injectBlueShiftPortfolio($, content) {
  const features = content.features.length ? content.features : [{ title: content.title, desc: content.subtitle }];
  const values = content.values.length ? content.values : features;
  const flow = content.flow.length ? content.flow : ["输入材料", "选择模板", "生成页面"];

  setBySlot($, "text.navbar.01", `${escapeHtml(content.title)} <span class="text-cyan-400">Inc.</span>`, true);
  setBySlot($, "text.hero.01", "DIGITAL PORTFOLIO & EDITABLE HTML");
  setBySlot($, "text.hero.02", `${escapeHtml(content.title)}<br>explore ;)`, true);
  setBySlot($, "text.hero.03", content.subtitle);
  setBySlot($, "text.hero.04", "01 / OVERVIEW");
  setBySlot($, "text.hero.05", "GENERATED AS LOCAL HTML");
  setBySlot($, "text.hero.06", "SCROLL DOWN TO ARCHIVE");

  setBySlot($, "text.philosophy.01", "02 / PHILOSOPHY");
  setBySlot($, "text.philosophy.02", `${content.title} 把核心材料转译为结构清晰、可编辑、可交付的单页官网。`);
  setBySlot($, "text.philosophy.03", "DESIGN METRIC");
  setBySlot($, "text.philosophy.04", values[0]?.title || "可编辑内容结构");
  setBySlot($, "text.philosophy.05", "MATERIALS RESEARCH");
  setBySlot($, "text.philosophy.06", values[0]?.desc || content.subtitle);
  setBySlot($, "text.philosophy.07", "COMPLETED MODULES");
  setBySlot($, "text.philosophy.08", "8 个页面模块 / 89 个可编辑槽位");

  setBySlot($, "text.works.01", "03 / CLASSIFIED PORTFOLIOS");
  fillSlotPairs($, features, [
    ["text.works.02", "text.works.03"],
    ["text.works.10", "text.works.11"],
    ["text.works.16", "text.works.17"]
  ]);
  const archiveItems = repeatItems(features.concat(values, flow.map((item) => ({ title: item, desc: "LOCAL HTML" }))), 9);
  archiveItems.forEach((item, index) => {
    const base = 4 + index * 2;
    setBySlot($, `text.works.${String(base).padStart(2, "0")}`, item.title);
    setBySlot($, `text.works.${String(base + 1).padStart(2, "0")}`, "LOCAL HTML");
  });

  setBySlot($, "text.methodology.01", "04 / PARAMETRIC PIPELINE");
  setBySlot($, "text.methodology.02", "METHODOLOGY<br><span class=\"text-dark-textDark font-normal text-lg tracking-normal\">TECHNICAL PIPELINE</span>", true);
  setBySlot($, "text.methodology.03", "从输入材料到页面生成，再到浏览器内编辑与导出，保留可追踪的内容生产链路。");
  flow.slice(0, 3).forEach((item, index) => {
    const phase = index + 1;
    const fallback = values[index] || features[index] || features[0];
    setBySlot($, `text.methodology.${String(4 + index * 3).padStart(2, "0")}`, `PHASE 0${phase}`);
    setBySlot($, `text.methodology.${String(5 + index * 3).padStart(2, "0")}`, item);
    setBySlot($, `text.methodology.${String(6 + index * 3).padStart(2, "0")}`, fallback?.desc || content.subtitle);
  });

  setBySlot($, "text.metrics.01", "05 / PERFORMANCE METRICS");
  setBySlot($, "text.metrics.02", "DYNAMIC DATA<br><span class=\"text-dark-textDark font-normal text-lg tracking-normal\">PUBLISHING STATUS</span>", true);
  setBySlot($, "text.metrics.03", "以下指标用于表达页面交付状态，不编造业务经营数据。");
  [
    ["HTML OUTPUT", "READY", "SINGLE FILE EXPORT"],
    ["EDITABLE SLOTS", "89", "TEXT NODES READY"],
    ["RUNTIME", "LOCAL", "NO SERVER REQUIRED"],
    ["CONTENT FLOW", "CLEAR", "SOURCE TO TEMPLATE"]
  ].forEach(([label, value, desc], index) => {
    const offset = 4 + index * 3;
    setBySlot($, `text.metrics.${String(offset).padStart(2, "0")}`, label);
    setBySlot($, `text.metrics.${String(offset + 1).padStart(2, "0")}`, value);
    setBySlot($, `text.metrics.${String(offset + 2).padStart(2, "0")}`, desc);
  });

  setBySlot($, "text.milestones.01", "06 / CHRONOLOGY");
  setBySlot($, "text.milestones.02", "PUBLISHING<br><span class=\"text-dark-textDark font-normal text-lg tracking-normal\">TIMELINE</span>", true);
  [
    ["text.milestones.03", "STEP 01"],
    ["text.milestones.04", flow[0] || "输入材料"],
    ["text.milestones.05", "CONTENT"],
    ["text.milestones.06", "STEP 02"],
    ["text.milestones.07", flow[1] || "选择模板"],
    ["text.milestones.08", "TEMPLATE"],
    ["text.milestones.09", "STEP 03"],
    ["text.milestones.10", flow[2] || "生成页面"],
    ["text.milestones.11", "HTML"],
    ["text.milestones.12", "STEP 04"],
    ["text.milestones.13", "编辑导出"],
    ["text.milestones.14", "EXPORT"]
  ].forEach(([slot, value]) => setBySlot($, slot, value));
  setBySlot($, "text.contact.01", "07 / INITIATE ENGAGEMENT");
  setBySlot($, "text.contact.02", "Let's publish<br>the editable page.", true);
  setBySlot($, "text.contact.03", `${content.title} 页面已生成，可继续在浏览器中编辑并导出 HTML。`);
  setBySlot($, "text.contact.04", "INLINE EDIT");
  setBySlot($, "text.contact.05", "LOCAL SAVE");
  setBySlot($, "text.contact.06", "HTML EXPORT");
  setBySlot($, "text.contact.07", "无需账号 · 无数据库 · 本地文件交付");
  setBySlot($, "text.contact.08", `© 2026 ${content.title}. Generated by AI HTML Publisher.`);
}

function replaceTextFragments($, replacements, scriptReplacements = []) {
  $("body")
    .find("*")
    .addBack()
    .contents()
    .each((_, node) => {
      if (node.type !== "text" || !node.data) return;
      let value = node.data;
      replacements.forEach(([from, to]) => {
        value = value.split(from).join(to);
      });
      node.data = value;
    });

  $("script:not([src])").each((_, element) => {
    const node = $(element);
    let value = node.html();
    scriptReplacements.forEach(([from, to]) => {
      value = value.split(from).join(to);
    });
    node.html(value);
  });
}

function fillDottedSlotPairs($, items, slots) {
  slots.forEach(([titleSlot, descSlot], index) => {
    const item = items[index] || items[0];
    if (!item) return;
    setBySlot($, titleSlot, item.title);
    setBySlot($, descSlot, item.desc);
  });
}

function fillSlotPairs($, items, slots) {
  slots.forEach(([titleSlot, descSlot], index) => {
    const item = items[index] || items[0];
    if (!item) return;
    setBySlot($, titleSlot, item.title);
    setBySlot($, descSlot, item.desc);
  });
}

function repeatItems(items, count) {
  const usable = items.filter(Boolean);
  if (!usable.length) return [];
  return Array.from({ length: count }, (_, index) => usable[index % usable.length]);
}

function setFooterLinks($, labels) {
  labels.forEach((label, index) => {
    setBySlot($, `footer-link-${index + 1}`, label);
  });
}

function fillKeyPairs($, items, keys) {
  keys.forEach(([titleKey, descKey], index) => {
    const item = items[index];
    if (!item) return;
    setByKey($, titleKey, item.title);
    setByKey($, descKey, item.desc);
  });
}

function fillFlowSteps($, flow) {
  flow.slice(0, 3).forEach((item, index) => {
    const step = index + 1;
    setByKey($, `workflow_step_${step}_num`, String(step).padStart(2, "0"));
    setByKey($, `workflow_step_${step}_title`, item);
    setByKey($, `workflow_step_${step}_desc`, step === 1
      ? "把明确材料输入系统。"
      : step === 2
        ? "选择页面类型和视觉模板。"
        : "生成后进入预览与编辑。");
  });
}

function sanitizeFiDecorations($) {
  replaceExactText($, {
    "SYSTEM.ONLINE": "LOCAL.READY",
    "VERSION_2.0.4": "HTML.EXPORT",
    Overview: "问题",
    Systems: "能力",
    Analytics: "流程",
    Config: "行动",
    "2085 / 05 / 20": "本地文件",
    "14:35:42": "可编辑",
    "[+] COORD_SYNC": "[+] TEMPLATE_READY",
    "LAT: 22.5726° N": "CONTENT_READY",
    "LON: 88.3639° E": "EDIT_READY",
    "TX_RATE: 2.45 TB/s": "EXPORT_READY",
    "# 探索未来界面设计语言": "# 使用模板生成可编辑页面",
    "SOURCE CODE": "编辑页面",
    "99.9%": "HTML",
    "界面指令响应率": "单文件可导出",
    "SYSTEM_LOAD (负载)": "EDIT_STATUS",
    "MODE: ADMIN": "MODE: EDITABLE",
    "OPERATOR: ROOT_USER": "OUTPUT: HTML",
    "SYS_UPTIME: 256d 14h 32m": "RUNTIME: LOCAL",
    "HASH: 0x8F9A2B": "STORAGE: LOCAL"
  });

  $('[data-editable="true"]').each((_, element) => {
    const node = $(element);
    if (node.text().trim() === "DATA STREAM ● LIVE") {
      node.html('PAGE STATUS <span class="blink text-white">● READY</span>');
    }
  });
}

function replaceExactText($, replacements) {
  $('[data-editable="true"]').each((_, element) => {
    const node = $(element);
    const text = node.text().trim();
    if (Object.prototype.hasOwnProperty.call(replacements, text)) {
      node.text(replacements[text]);
    }
  });
}

function fillTriplet($, items, keys) {
  keys.forEach(([titleKey, descKey], index) => {
    const item = items[index];
    if (!item) return;
    setByKey($, titleKey, item.title);
    setByKey($, descKey, item.desc);
  });
}

function fillPairs($, section, titleSelector, descSelector, items) {
  const root = $(`[data-section="${section}"]`);
  const titles = root.find(titleSelector);
  const descs = root.find(descSelector);

  items.forEach((item, index) => {
    if (titles.eq(index).length) setText(titles.eq(index), item.title);
    if (descs.eq(index).length) setText(descs.eq(index), item.desc);
  });
}

function setByKey($, key, value, asHtml = false) {
  const node = $(`[data-key="${key}"]`).first();
  if (!node.length || !value) return;
  if (asHtml) node.html(value);
  else setText(node, value);
}

function setBySlot($, slot, value, asHtml = false) {
  const node = $(`[data-slot="${slot}"]`).first();
  if (!node.length || !value) return;
  if (asHtml) node.html(value);
  else setText(node, value);
}

function setText(node, value) {
  if (!node.length || !value) return;
  node.text(value);
}

function removeSections($, sections) {
  sections.forEach((section) => {
    $(`[data-section="${section}"]`).remove();
  });
}

function removeFakeLinks($) {
  $('a[href="#"]').removeAttr("href");
}

function sanitizeGeneratedOutput($) {
  normalizeExternalAssets($);
  removeInlineEventHandlers($);
  replaceTextFragments($, [
    ["EFFICIENCY:", "OUTPUT:"],
    ["99.8%", "READY"],
    ["SLA 99.9% / 5x8 专家支持", "HTML 导出 / 本地编辑"],
    ["PEAK QPS ROUTING", "PAGE STATUS READY"],
    ["nous/core-agent", "ai-html-publisher/page"]
  ]);
}

function normalizeExternalAssets($) {
  $('link[href*="fonts.googleapis.com"], link[href*="fonts.gstatic.com"]').remove();
  $('link[rel="preconnect"][href*="fonts.googleapis.com"], link[rel="preconnect"][href*="fonts.gstatic.com"]').remove();
  $("style").each((_, element) => {
    const node = $(element);
    const cleaned = node.html()
      .replace(/^\s*@import\s+url\([^)]*fonts\.googleapis\.com[^)]*\);\s*$/gm, "")
      .replace(/@import\s+url\([^)]*fonts\.googleapis\.com[^)]*\);\s*/g, "");
    if (cleaned !== node.html()) node.html(cleaned);
  });
}

function cleanKnownInternalRemnants($) {
  replaceTextFragments($, [
    ['base_url="http://localhost:8080/v1"', 'output="local editable html"'],
    ["http://localhost:8080/v1", "local editable html"]
  ]);
}

async function inlineTailwindStyles($) {
  const tailwindScripts = $('script[src^="https://cdn.tailwindcss.com"]');
  if (!tailwindScripts.length) return;

  const tempDir = await mkdtemp(path.join(tmpdir(), "ai-html-publisher-tailwind-"));
  const contentPath = path.join(tempDir, "content.html");
  const inputPath = path.join(tempDir, "input.css");
  const outputPath = path.join(tempDir, "tailwind.css");
  const configPath = path.join(tempDir, "tailwind.config.cjs");

  try {
    await writeFile(contentPath, $.html(), "utf8");
    await writeFile(inputPath, "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n", "utf8");
    await writeFile(configPath, tailwindConfigSource($, contentPath), "utf8");
    await execFileAsync(process.execPath, [
      TAILWIND_CLI_PATH,
      "-c",
      configPath,
      "-i",
      inputPath,
      "-o",
      outputPath,
      "--minify"
    ], { cwd: process.cwd(), maxBuffer: 20 * 1024 * 1024 });

    const css = await readFile(outputPath, "utf8");
    tailwindScripts.remove();
    removeTailwindConfigScripts($);
    $("head").append(`\n<style data-ahp-inlined-tailwind="true">${css}</style>`);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

function tailwindConfigSource($, contentPath) {
  const configLiteral = extractTailwindConfigLiteral($) || "{}";
  return [
    `"use strict";`,
    `const config = ${configLiteral};`,
    `config.content = [${JSON.stringify(contentPath)}];`,
    `module.exports = config;`
  ].join("\n");
}

function extractTailwindConfigLiteral($) {
  let literal = "";
  $("script:not([src])").each((_, element) => {
    if (literal) return;
    const code = $(element).html() || "";
    const assignment = code.indexOf("tailwind.config");
    if (assignment === -1) return;
    const start = code.indexOf("{", assignment);
    if (start === -1) return;
    literal = readBalancedObjectLiteral(code, start);
  });
  return literal;
}

function readBalancedObjectLiteral(source, start) {
  let depth = 0;
  let quote = "";
  let escaped = false;
  for (let index = start; index < source.length; index += 1) {
    const char = source[index];
    if (quote) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === quote) quote = "";
      continue;
    }
    if (char === '"' || char === "'" || char === "`") {
      quote = char;
      continue;
    }
    if (char === "{") depth += 1;
    if (char === "}") {
      depth -= 1;
      if (depth === 0) return source.slice(start, index + 1);
    }
  }
  return "{}";
}

function removeTailwindConfigScripts($) {
  $("script:not([src])").each((_, element) => {
    const node = $(element);
    if ((node.html() || "").includes("tailwind.config")) node.remove();
  });
}

function removeInlineEventHandlers($) {
  $("*").each((_, element) => {
    const node = $(element);
    Object.keys(element.attribs || {}).forEach((name) => {
      if (/^on/i.test(name)) node.removeAttr(name);
    });
  });
}

function stripTemplateEditorArtifacts($) {
  $("style").each((_, element) => {
    const node = $(element);
    const cleaned = node.html().replace(/\/\*\s*模拟 AI 工具的在线可编辑框样式\s*\*\/[\s\S]*?\[data-editable="true"\]:focus\s*\{[\s\S]*?\}\s*/g, "");
    if (cleaned !== node.html()) node.html(cleaned);
  });

  $("body div").each((_, element) => {
    const node = $(element);
    const text = node.text();
    if (text.includes("Visual Template Preview") || text.includes("即时编辑模式已开通")) {
      node.remove();
    }
  });

  $("script:not([src])").each((_, element) => {
    const node = $(element);
    const cleaned = node.html().replace(/\n\s*\/\/\s*3\.[^\n]*\n\s*document\.querySelectorAll\('\[data-editable="true"\]'\)\.forEach\(el => \{\s*\n\s*el\.setAttribute\('contenteditable', 'true'\);\s*\n\s*\}\);\s*/g, "\n");
    if (cleaned !== node.html()) node.html(cleaned);
  });
}

function assignEditIds($) {
  $('[data-editable="true"]').each((index, element) => {
    const node = $(element);
    node.attr("data-edit-id", `edit-${index + 1}`);
    node.removeAttr("contenteditable");
  });
}

function injectRuntime($, title, templateId, themeColor, themeConfig) {
  const initial = $('[data-editable="true"][data-edit-id]')
    .map((_, element) => ({
      id: $(element).attr("data-edit-id"),
      html: $(element).html(),
      style: $(element).attr("style") || "",
      href: $(element).attr("href") || $(element).closest("a").attr("href") || $(element).attr("data-link-url") || ""
    }))
    .get();
  const storageKey = `ai-html-publisher:${slug(templateId)}:${slug(title)}`;

  $("head").append(`\n<style data-ahp-runtime="true">${runtimeStyle()}</style>`);
  $("body").append(`\n<script data-ahp-runtime="true">${runtimeScript(initial, storageKey, templateId, themeColor, themeConfig)}</script>`);
}

function templateThemeColor(config, templateId) {
  const configured = normalizeHex(config?.editorTheme?.defaultColor);
  if (configured) return configured;

  const explicit = {
    "website-01-fui": "#ffffff",
    "website-02-soft-surrealism": "#1d70b8",
    "website-03-red-clay": "#d9eb26",
    "website-04-premium-midnight": "#7c3aed",
    "website-05-voltflow-cyber-saas": "#7cff44",
    "website-07-blueprint-agent-platform": "#0012e8",
    "website-08-editorial-apple-tech": "#8da4c2",
    "website-09-blue-shift-portfolio": "#00f2fe"
  };
  if (explicit[templateId]) return explicit[templateId];

  const colors = config?.theme?.colors || {};
  for (const key of ["accent", "primary", "brand", "indigo", "purple", "skyStart", "pageBg", "textPrimary"]) {
    const value = normalizeHex(colors[key]);
    if (value) return value;
  }
  return "#ffffff";
}

function templateThemeConfig(config, defaultColor) {
  const editorTheme = config?.editorTheme || {};
  const targets = editorTheme.targets || {};
  const presets = Array.isArray(editorTheme.presets) ? editorTheme.presets : [];
  return {
    defaultColor,
    presets,
    targets: {
      cssVariables: targets.cssVariables || {},
      colorSelectors: targets.colorSelectors || [],
      backgroundSelectors: targets.backgroundSelectors || [],
      borderSelectors: targets.borderSelectors || [],
      shadowSelectors: targets.shadowSelectors || [],
      gradientSelectors: targets.gradientSelectors || [],
      radialGlowSelectors: targets.radialGlowSelectors || [],
      strokeSelectors: targets.strokeSelectors || [],
      fillSelectors: targets.fillSelectors || [],
      stopColorSelectors: targets.stopColorSelectors || []
    }
  };
}

function normalizeHex(value) {
  const text = String(value || "").trim();
  return /^#[0-9a-fA-F]{6}$/.test(text) ? text.toLowerCase() : "";
}

function slug(text) {
  return String(text || "page").trim().toLowerCase().replace(/\s+/g, "-").slice(0, 60);
}

function escapeHtml(text) {
  return String(text || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
